Use guard clauses to reduce nesting
pardus/pardus-image-writer pull request #4
Opened 2023-02-13 19:21 UTC by xeome

Use guard statements and inverted if statements to reduce nesting in code and make it easier to understand. Guard statements are statements placed at the beginning of a function that check whether certain conditions are met and return a value immediately if they are not. Inverted if statements are if statements written in such a way that the "happy path" is written first, followed by error handling.

These techniques help to make code more readable and maintainable, as they reduce the amount of indentation and make it easier to follow the flow of the code. It can be difficult to understand what is going on in a nested structure, but by using guard statements and inverted if statements we can simplify the code and make it more intuitive.

2023-02-13 19:52 UTC, eminfedar commented on src/MainWindow.py
> +            self.writeMode = "ImageWriter.py"
Please add `return` after this line and remove Line 182-183.

2023-02-13 19:52 UTC, eminfedar commented on src/MainWindow.py
> +            return
Remove this and add this return to first if == 0 clause.

2023-02-13 19:58 UTC, eminfedar commented on src/main.py
> +            print("File not exists : " + file.get_path())
Little translation fix (not your fault)
```suggestion
            print("File does not exist: " + file.get_path())
```

2023-02-13 20:00 UTC, eminfedar requested changes
I think this PR is good. Guard clauses are "generally" good practice.

I just mentioned couple changes. After you fix these, this PR seems good to me.

2023-02-13 20:12 UTC, xeome commented
Thanks for the suggestions, I have made the changes that you requested.

2023-02-13 20:14 UTC, eminfedar commented
Thanks for your efforts @xeome.

@fthaltun it seems Ok to me.

2023-02-14 14:26 UTC, fthaltun commented
Thanks for your contribution @xeome.
Also thanks @eminfedar.

2023-02-14 14:26 UTC, merged