Create a proper readme
pardus/pardus-image-writer pull request #5
Opened 2023-02-13 19:48 UTC by xeome

Create a readme with information about dependencies, installation, features.

2023-02-13 20:03 UTC, eminfedar commented on README.md
> +pardus-image-writer is a simple and user-friendly tool for writing image files to removable storage devices. It's designed to be fast, reliable, and easy to use, making it the perfect solution for an
I think the summary at Line 4 is sufficient. You can remove this.

2023-02-13 20:05 UTC, eminfedar commented on README.md
> +- Cross-platform compatibility: pardus-image-writer is written in Python, works on many linux distributions.
Cross Platform compatibility generally means: "it works Windows, Linux & macOS"

This is "Linux" only.

2023-02-13 20:10 UTC, eminfedar commented on README.md
> +To install pardus-image-writer, follow these steps:
Installing from .deb files is easy to handle for end users.

These steps can be written as a second alternative.

Please add these steps above:
```suggestion
1. Download the latest version of .deb file from [Releases](https://github.com/pardus/pardus-image-writer/releases) page.
2. Install the .deb file with Pardus Package Installer by double clicking on it. (or use `sudo apt install pardus-image-writer_0.4.0.Beta1_all.deb`)
```

2023-02-13 20:11 UTC, eminfedar requested changes
I requested some changes. After the changes, this PR is good to me.

2023-02-13 20:24 UTC, xeome commented
Hello, thanks for the suggestions, I have made the changes that you requested with minor additions.

2023-02-14 14:38 UTC, fthaltun commented
We were thinking of using a standard readme template in all pardus projects. We were going to implement this in the near future; If you want, you can send a request by following the examples below.

For example;
https://github.com/pardus/pardus-mycomputer/blob/master/README.md
https://github.com/pardus/pardus-software/blob/master/README.md

2023-04-23 18:10 UTC, closed without merging